version: '3'

services:
  backend:
    container_name: nest-api
    build:
      context: .
      target: development
    restart: always
    volumes: 
      - .:/usr/src/app
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE

    network_mode: host
    command: npm run start:dev
    
volumes:
  postgres-data: 