version: '3'

services:
  backend:
    container_name: backend
    image: nest-api
    depends_on: 
      - postgres
    ports:
      - "5000:5000"
    build:
      context: .
      target: development
    networks:
      - nwebnetesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:13.2-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
    webnet:
