version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      target: development
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    env_file: .env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: npm run start:dev
    
networks:
    nesjs-network:
